server:
  port: 8080
spring:
  application:
    name: customer
  datasource:
    password: 5168
    #    url: jdbc:postgresql://localhost:5432/customer
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/customer
  jpa:
    hibernate:
      #      ddl-auto: create-drop- do not use this in production
      ddl-auto: create-drop
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.MySQl8LDialect
        format_sql: true
    show-sql: true

eureka:
      client:
          service-url:
              defaultZone: http://localhost:8761/eureka
          fetch-registry: true
          register-with-eureka: true
          enabled: true